# Generated by Django 5.0.2 on 2024-02-29 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb_Reg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='user',
        ),
        migrations.AddField(
            model_name='biodata',
            name='e_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='biodata',
            name='e_contact',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='biodata',
            name='e_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='biodata',
            name='e_relationship',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(max_length=100)),
                ('subject2', models.CharField(max_length=100)),
                ('subject3', models.CharField(max_length=100)),
                ('subject4', models.CharField(max_length=100)),
                ('result1', models.CharField(max_length=1)),
                ('result2', models.CharField(max_length=1)),
                ('result3', models.CharField(max_length=1)),
                ('result4', models.CharField(max_length=1)),
                ('resultSheet', models.FileField(upload_to='')),
                ('degreeName', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('gpa', models.CharField(max_length=100)),
                ('degreeClass', models.CharField(max_length=100)),
                ('degreestartYear', models.CharField(max_length=5)),
                ('graduateYear', models.CharField(max_length=5)),
                ('transcript', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AdvancedLevel',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Emergency',
        ),
    ]
