# Generated by Django 5.0.2 on 2024-03-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb_Reg', '0002_remove_degree_user_remove_emergency_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifications',
            name='al_year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
