# Generated by Django 5.0.2 on 2024-03-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb_Reg', '0003_qualifications_al_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifications',
            name='stream',
            field=models.CharField(default='', max_length=100),
        ),
    ]
