# Generated by Django 5.0.2 on 2024-03-06 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb_Reg', '0004_qualifications_stream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('journal', models.CharField(max_length=100)),
                ('publicationDate', models.DateField(blank=True, default='', null=True)),
                ('abstract', models.CharField(max_length=200)),
                ('title2', models.CharField(default='', max_length=100)),
                ('authors2', models.CharField(default='', max_length=100)),
                ('journal2', models.CharField(default='', max_length=100)),
                ('publicationDate2', models.DateField(blank=True, default='', null=True)),
                ('abstract2', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
