# Generated by Django 5.0.2 on 2024-03-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb_Reg', '0005_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publicationDate',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publicationDate2',
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(default='', max_length=200),
        ),
    ]
