# Generated by Django 5.0.2 on 2024-03-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmb_Reg', '0007_publication_doi2'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrees',
            name='r1_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='refrees',
            name='r2_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
